markdown: kramdown
include:
  [
    "android-chrome-192x192.png",
    "android-chrome-512x512.png",
    "apple-touch-icon.png",
    "favicon-16x16.png",
    "site.webmanifest",
    "favicon.ico",
  ]
